[package]
name = "profiler-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mprofiler-proto = { path = "../mprofiler-proto" }
tonic = { version = "0.12", features = ["zstd"] }
prost = "0.13"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "process", "io-util"] }
tokio-stream = "0.1"
widestring = "1.0"
parking_lot = "0.12"
once_cell = "1.19"
log = "0.4"
log4rs = "1"
anyhow = "1.0"
regex = "1.10"
crossbeam-queue = "0.3"
tokio-util = "0.7"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_System_Diagnostics_Debug", "Win32_System_Kernel"] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
